### ISSUE TITLE
Cant pull, cloudflare error

### ISSUE THREAD

**Issue by shorty789** [sonroyaalmerol/m3u-stream-merger-proxy#1]
unfortunately I cannot pull this via docker as i encounter a cloudflare issue. 

"This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data."

**Comment by sonroyaalmerol** [comment]
Hi @shorty789. I've migrated over to Docker Hub to make things easier for you. Try using `sonroyaalmerol/m3u-stream-merger-proxy:latest`.

**Comment by shorty789** [comment]
Awesome, that seems to work great now, I will get to having a deeper play with it later. Thank you very much for such a rapid response.

Can I provide a suggestion too? It would be absolutely amazing if you could set a max simultaneous stream limit per playlist.

An example would be the ability to give one of the streams a maximum of 3 users, while another one a maximum of one user, it would then be great to be able to merge those playlists into a single one that can support 4 simultaneous streams, with the 5th attempt to connect either redirecting to some 'catch all' stream, or just refusing to connect entirely. Not sure how easy it would be to implement though to be honest.

**Comment by sonroyaalmerol** [comment]
> Can I provide a suggestion too? It would be absolutely amazing if you could set a max simultaneous stream limit per playlist.
> 
> An example would be the ability to give one of the streams a maximum of 3 users, while another one a maximum of one user, it would then be great to be able to merge those playlists into a single one that can support 4 simultaneous streams, with the 5th attempt to connect either redirecting to some 'catch all' stream, or just refusing to connect entirely. Not sure how easy it would be to implement though to be honest.

That sounds good and is definitely within the scope of the project. Do you mind issuing a different ticket for this one? I'll be closing this current one as completed. Thanks!
