### ISSUE TITLE
Failed Stream Notifier

### ISSUE THREAD

**Issue by kpirnie** [sonroyaalmerol/m3u-stream-merger-proxy#101]
Any way a "This Stream Has Failed" image or looping vid could be added in for when a stream fails?

**Comment by sonroyaalmerol** [comment]
This is something I'm not 100% sure if it's feasible without using ffmpeg and I'd like to avoid using it just for this feature (pretty overkill).

**Comment by kpirnie** [comment]
> This is something I'm not 100% sure if it's feasible without using ffmpeg and I'd like to avoid using it just for this feature (pretty overkill).

:)
I would just inject a public URL to a tiny looping video ;)

**Comment by sonroyaalmerol** [comment]
That would not guarantee that the tiny looping video will have the same encoding as the previously running stream which will confuse the client running the stream. The tiny looping video should match the mime-type initially sent via the HTTP header which is derived from the original source stream that "failed".

However, I've never really tried it as I figured it would be a pain if my assumptions above are correct.

**Comment by kp-emagine** [comment]
> That would not guarantee that the tiny looping video will have the same encoding as the previously running stream which will confuse the client running the stream. The tiny looping video should match the mime-type initially sent via the HTTP header which is derived from the original source stream that "failed".
> 
> However, I've never really tried it as I figured it would be a pain if my assumptions above are correct.

Maybe I'll give it a shot in my fork ;)   I want to learn Go anyways, it'd be a good excercise.   Same with integrating ffmpeg... for some clients, i can see that being beneficial, but it would make the container's pretty big if I do it the way I'm thinking lololol

**Comment by sonroyaalmerol** [comment]
Sure! Feel free to create a PR for this if you're able to figure out an easy way to do it. I'm not planning on doing this anytime soon

**Comment by kpirnie** [comment]
:)
Got a couple cool mini-vids through AI now...

https://n1u5.c15.e2-5.dev/kp-cdn/channel-offline-1.mp4
https://n1u5.c15.e2-5.dev/kp-cdn/channel-offline-2.mp4

I really like that first one, other than AI spelt channel wrong in it lol
