### ISSUE TITLE
Stream Timeout Env. Var.

### ISSUE THREAD

**Issue by kpirnie** [sonroyaalmerol/m3u-stream-merger-proxy#102]
Can we get an environment variable for the container to specify how long the proxy should take before calling a stream "bad"?  Maybe default to 3 seconds?

**Comment by sonroyaalmerol** [comment]
Can you test PR #112 if it works for you? You can use the image URL provided in the PR for your convenience. As suggested, the default is 3 seconds but is adjustable with the `STREAM_TIMEOUT` env var.

**Comment by kpirnie** [comment]
> Can you test PR #112 if it works for you? You can use the image URL provided in the PR for your convenience. As suggested, the default is 3 seconds but is adjustable with the `STREAM_TIMEOUT` env var.

Seems good.    lol, had to dig thru some streams to actually find a bad one, but it seems to have timed out properly.

tested a couple times with 5 and 7 seconds as well

**Comment by sonroyaalmerol** [comment]
Merged and released! Closing this issue as resolved.

**Comment by kpirnie** [comment]
Unsure if this is related to this issue or not.  Ended up running into this... after around 200 lines like this in the log, the next stream finally plays
![Screenshot_1](https://github.com/user-attachments/assets/7ead0edf-1ff1-4ae6-9bb3-58ebbc88c975)
