### ISSUE TITLE
Multiple Containers

### ISSUE THREAD

**Issue by kpirnie** [sonroyaalmerol/m3u-stream-merger-proxy#103]
This is sort-of a bug, but not really.   

I'd like to be able to run more than 1 container at different ports to parse different m3u's.   For instance, I have my "shows" playlist, and I have a separate "live" playlist.

Running 2 containers at separate ports right now, only allows 1 playlist to be exported from the proxy.  Maybe base the database on the containers host port?

**Comment by sonroyaalmerol** [comment]
You can use different Redis database indexes each for this use-case. For example, you can set `REDIS_DB=0` for one playlist then have `REDIS_DB=1` for the other.

**Comment by kpirnie** [comment]
Yeah, i'm blind... just read this in the code lololol
