### ISSUE TITLE
is there a wiki or plans for adding one? i have some questions

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#106]
1) `LOAD_BALANCING_MODE (removed on version 0.10.0)`: does this means we dont have this feature anymore at all?
2) `PARSER_WORKERS`: what is a good number for this aside from the default one. what is this use for and the benefit of using a higher number?
3) `BUFFER_MB`: default is none, if set two 1, 2, etc. would watching for example the same channel 2x+ make it where only 1 cxn is required from the provider?
4) `TITLE_SUBSTR_FILTER`: what does this does? can i get an example?
5) how can i do fail over? is it done at the channel level (base on channel having the same name, or tvg id, etc?
6) is it possible to do group and channel merging, renaming, etc on the fly?

**Comment by sonroyaalmerol** [comment]
> 1. `LOAD_BALANCING_MODE (removed on version 0.10.0)`: does this means we dont have this feature anymore at all?

Yes. It was a pain to maintain.

> 2. `PARSER_WORKERS`: what is a good number for this aside from the default one. what is this use for and the benefit of using a higher number?

I would say a good reference would be your CPU thread count. The parsing process is done asynchronously. Each worker does its job to parse the M3U lines and "convert" them to something the proxy can easily read. Think of it as the number of parallel jobs you want running during the parsing process.

> 3. `BUFFER_MB`: default is none, if set two 1, 2, etc. would watching for example the same channel 2x+ make it where only 1 cxn is required from the provider?

No. That is not the purpose of the proxy's buffer. It is only there to smoothen out the stream. Use other services like Threadfin/xTeVe which uses ffmpeg to actually read the video streams and buffer them appropriately. This proxy is meant to be dumb and has no capabilities to "read" or understand what data it is passing on to the client.

> 4. `TITLE_SUBSTR_FILTER`: what does this does? can i get an example?

This basically removes any string that matches the regular expression from the stream titles. Most common use-case is to remove country codes from the title. See this cheat sheet and play around with it if you need: https://yourbasic.org/golang/regexp-cheat-sheet/

> 5. how can i do fail over? is it done at the channel level (base on channel having the same name, or tvg id, etc?

It uses the channel title or tvg-name (as fallback) to merge multiple identical channels into one. This has been explained in the [README](https://github.com/sonroyaalmerol/m3u-stream-merger-proxy#how-it-works).

> 6. is it possible to do group and channel merging, renaming, etc on the fly?

The primary use-case for this proxy is to merge multiple identical M3Us from the same provider. Some IPTV providers give out one M3U playlist for each cxn you buy from them. If you want more customizability, use Threadfin with this proxy.

I will eventually create a better documentation but I'm focused on getting the actual features working first. I would appreciate any PRs to help with documentation.

**Comment by aniel300** [comment]
ok thank u for taking the time to answer this, i think i understand everything now, keep up the good work and thank you again.
