### ISSUE TITLE
ability to sync providers from a ".txt" list

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#107]
ability to sync providers from a ".txt" list. something like `M3U_URL_1=/xxx/xxx/userdefinedname.txt` where "userdefinedname.txt" would have the providers urls inside on a per line basis, thank you.

**Comment by sonroyaalmerol** [comment]
What is your use case for this?

**Comment by aniel300** [comment]
i would like to try something if this gets implemented...the ability to use different tiers of providers in an easy fashion without having to do 1 one by one in the compose file.

**Comment by sonroyaalmerol** [comment]
Sorry but it doesn't seem worth my time to implement and maintain. Use env files and import that to your compose file with the `env_file` attribute if that makes it easier for you.
