### ISSUE TITLE
Retrying same stream

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#113]
`Retrying same stream until timeout (3 seconds) is reached...` can u make this user customizable, specially i would like to try 1ms or 1s, thank you.

**Comment by kpirnie** [comment]
> `Retrying same stream until timeout (3 seconds) is reached...` can u make this user customizable, specially i would like to try 1ms or 1s, thank you.

It already is
https://github.com/sonroyaalmerol/m3u-stream-merger-proxy/issues/102

**Comment by aniel300** [comment]
nice, let me try it and also close this for now then, thanks.

**Comment by aniel300** [comment]
@kpirnie do u know if this supports `ms`?

**Comment by kpirnie** [comment]
> @kpirnie do u know if this supports `ms`?

does not look it.  Looks like an integer, so only whole number seconds will work as well

**Comment by aniel300** [comment]
will try with 1s if not i will open this and see if it possible to use `ms`

**Comment by aniel300** [comment]
anyway to make this work at the ms level. i would like to try 1ms since am still getting skip backs? @sonroyaalmerol

**Comment by aniel300** [comment]
strangely am seeing this issue with one client andoird iptv client but not with vlc

**Comment by sonroyaalmerol** [comment]
Hmmm, making this work at the ms level won't really help with your issue and doesn't really make sense either. I'll close this issue and reopen your previous issue instead.
