### ISSUE TITLE
failover question

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#114]
does the failover work across different domains for the same provider?

**Comment by kpirnie** [comment]
> does the failover work across different domains for the same provider?

It works if there is an issue pulling the stream.  Period.

So... regardless of the domain it resides on, if the request throws a 404, 500, 403, etc... status code, the stream is considered dead and moves on fo the next.

Note... there is no "checking" of the stream itself.  That requires ffmpeg, and will significantly slow the loading down as ffmpeg needs to load the actual stream, test if for validity, then test it for content.

**Comment by aniel300** [comment]
yep, i don't think i need to test the stream itself but was wondering if it would work across different domains. will close this then, thanks
