### ISSUE TITLE
sync issue

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#132]
am not sure if this is a bug/issue or not but i have notice that msmp would sync news groups and probably news channels but it will not remove removed ones at the provider level. and i know there is `CLEAR_ON_BOOT` but when i use that option the db stays at 1kb and nothing happens. is there a way to make it where it syncs not only added but removes as well?

**Comment by sonroyaalmerol** [comment]
Good catch, I totally missed the removal portion of the sync. I'll update you when I implement the fix. Thanks!

**Comment by sonroyaalmerol** [comment]
`CLEAR_ON_BOOT` should now be working properly in the dev build. Closing this issue.

**Comment by aniel300** [comment]
i think there was two issue in this post, were u able to fix both?
