### ISSUE TITLE
ability to turn off "STREAM_TIMEOUT" and the "backoff" feature?

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#140]
can u add the ability to turn off the "STREAM_TIMEOUT" and the "backoff" feature?

**Comment by kpirnie** [comment]
change your containers `STREAM_TIMEOUT` to 0

**Comment by aniel300** [comment]
i have it already but i still see those other feature in action as well

**Comment by kpirnie** [comment]
> i have it already but i still see those other feature in action as well

still see the backoff in action?

In all honesty, you should have a stream timeout set.  Why would you want to sit indefinately staring at a blank screen if one of your streams goes down?

I would start at 3 second timeout, then work up to 10 seconds... if the stream hasn't timed out by then, or hasn't started playing by then... it won't and should be considered a dead stream... and then move to the next in the group

**Comment by aniel300** [comment]
yes i think the backoff feature is part of the `STREAM_TIMEOUT` one and yes `STREAM_TIMEOUT` if not set/ define then it defaults to 3s.

**Comment by sonroyaalmerol** [comment]
Merged #143. You should be able to set `STREAM_TIMEOUT` to 0 now. Setting this will force the proxy to skip retrying the same stream and will cycle through the other M3Us immediately instead.

**Comment by aniel300** [comment]
thank u trying now
