### ISSUE TITLE
ability not to sync vod (movies and tv shows) from m3u sync

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#141]
is possible to add the ability to choose not to sync vod (movies and tv shows) from the m3u sync process?

**Comment by kpirnie** [comment]
You should filter those out prior to passing them to the proxy.

Adding filters into this app changes it greatly, and you would have to supply your own filters.  

For instance, I have some that are specified with a group title, and alot that are not, but may contain a VOD in the name, or a `/vod` in the stream URL itself.  Others are ONLY specified because there is a video file extension at the end of the URL.

The above may or may not be the case in your specific instance.

**Comment by aniel300** [comment]
i believe my m3u provider use '.../movie/...' and '.../series/...' for movies and tv shows respectively. i could use iptvboss, iptveditor or sm to filter them out before hand but i really wanted to use msmp>sm>client as my set up.

**Comment by kpirnie** [comment]
Aye, that's really not what this app is for. There's way too many variable that would come into play, in addition there's no way to globalize a series of filters.  What works for you and your provider would not work for me and mine ;)

**Comment by aniel300** [comment]
true i agree. i belive some providers that dont use the standards i mentioned above but it was worth a shot. am waiting for the dev to say something...if this is a no go, then that is ok.

**Comment by kpirnie** [comment]
> true i agree. i belive some providers that dont use the standards i mentioned above but it was worth a shot. am waiting for the dev to say something...if this is a no go, then that is ok.

you have a windows machine?  i have a great app for ya.    i used to use it to curate mine (i built a website for myself to automatically do it now...)... hit me up in the Discord

**Comment by aniel300** [comment]
i couldn't find ur discord in ur prefile, sent u a messenger message asking for ur discord

**Comment by sonroyaalmerol** [comment]
You should be able to reach @kpirnie in the discord server as well: https://discord.com/invite/b2hVjRvkcj

The best I can do is probably implement a regex filter feature to exclude specific streams based on its title or URL during import.

**Comment by aniel300** [comment]
yes that should work. and i just confirm and all my provider use this as part of their standards just fyi `.../movie/...` and `.../series/...`

**Comment by kpirnie** [comment]
What about utlizing the existing: `TITLE_SUBSTR_FILTER` ??

**Comment by aniel300** [comment]
i don't fully understand this env so idk where to look or how to make it work. for the sound of it this for something related to names so am not sure.

**Comment by aniel300** [comment]
as per latest dev, this might not be needed anymore at this time, at least for me. closing for now.
