### ISSUE TITLE
unable to access .../playlist.m3u with latest dev

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#146]
unable to access .../playlist.m3u with latest dev. latest working dev for me was https://github.com/sonroyaalmerol/m3u-stream-merger-proxy/pull/143

**Comment by kpirnie** [comment]
Weird.  I just pulled and ran fine.  try restarting redis on your machine to fully clear it.

**Comment by kpirnie** [comment]
> unable to access .../playlist.m3u with latest dev. latest working dev for me was #143

actually... maybe you can pull it with: `docker pull ghcr.io/sonroyaalmerol/m3u-stream-merger-proxy:pr-143` ??

**Comment by aniel300** [comment]
i believe i tried but et me try again

**Comment by aniel300** [comment]
> ghcr.io/sonroyaalmerol/m3u-stream-merger-proxy:pr-143

didnt work 
![image](https://github.com/user-attachments/assets/6638cde4-0e0a-4afa-8183-2f12616fd5d2)

**Comment by sonroyaalmerol** [comment]
Are the logs the same as the ones you posted in the discussion?

**Comment by aniel300** [comment]
nope logs look fine...strangely

**Comment by aniel300** [comment]
actually never mind this regular looking logs are for the small testing channel number and other logs i got from the bid db but then again those logs were from 144 and this regular logs are from latest dev

**Comment by sonroyaalmerol** [comment]
Merged #148. Can you try the latest dev?

**Comment by sonroyaalmerol** [comment]
As discussed on Discord, it was an issue with `CACHE_ON_SYNC`. `CACHE_ON_SYNC` and `BASE_URL` are now fixed on the latest dev.

**Comment by aniel300** [comment]
can they now be enabled/ used?

**Comment by sonroyaalmerol** [comment]
Yes, they should be working as expected now. base url is still mandatory if `CACHE_ON_SYNC` is used.

**Comment by aniel300** [comment]
ok sounds good to me. will test and report back

**Comment by aniel300** [comment]
check the discord message. but yeah i will wait patiently. btw i haven't been able to test out the bid db because this issue. hope u have a wonderful day and are able to find a solution to this.

**Comment by aniel300** [comment]
i believe the issue have been fixed, closing for now, thanks bud.
