### ISSUE TITLE
Latest dev version currently in a boot loop

### ISSUE THREAD

**Issue by shorty789** [sonroyaalmerol/m3u-stream-merger-proxy#147]
I am using the latest dev version and I am currently stuck in a reboot loop, this is the error I am getting:

2024/08/28 14:02:25 [DEBUG] Next line: ***************
2024/08/28 14:02:25 [DEBUG] M3U index: 1
2024/08/28 14:02:25 [DEBUG] Processing attribute: tvg-name=***************
2024/08/28 14:02:25 [DEBUG] Processing attribute: tvg-logo=***************
2024/08/28 14:02:25 [DEBUG] Processing attribute: group-title=***************
2024/08/28 14:02:25 [DEBUG] Line comma split detected, title:***************
2024/08/28 14:02:25 [DEBUG] Processing attribute:***************
2024/08/28 14:02:25 [DEBUG] Worker processing stream info:***************
2024/08/28 14:02:25 [DEBUG] Processing attribute: tvg-name=***************
2024/08/28 14:02:25 [DEBUG] Worker processing stream info:***************
2024/08/28 14:02:25 [DEBUG] Worker processing stream info:***************
fatal error: 2024/08/28 14:02:25 [DEBUG] Worker processing stream info: ***************
concurrent map read and map write
2024/08/28 14:02:25 [DEBUG] Worker processing stream info: ***************

If you need the rest of the output let me know, i cut the rest of the log for brevity, but it would appear as though there is a problem processing the m3u as it currently stands.

**Comment by sonroyaalmerol** [comment]
Merged #148. Can you try the latest dev?

**Comment by sonroyaalmerol** [comment]
I've confirmed this to be fixed on the latest dev. Feel free to reopen if that is not the case for you.
