### ISSUE TITLE
MAX_RETRIES rate

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#153]
i dont know how the `MAX_RETRIES` works in the background but am assuming it get triggered by stream errors. is there a way to choose the rate at which it gets triggered. similar to how we can with `STREAM_TIMEOUT`?

**Comment by sonroyaalmerol** [comment]
Can you explain how this would help your use case/scenario? I'm not really sure how this will be used.

**Comment by aniel300** [comment]
this ties back (i think) to the post i made about the skips back and why not, as it stands right now it makes the streams robust but occasionally i get this and i was wondering if this would make a difference. what is the current behavior as to when `MAX_RETRIES` gets triggered?

**Comment by aniel300** [comment]
@sonroyaalmerol anyway you can implement this, please?

**Comment by sonroyaalmerol** [comment]
Yes, I will test out some implementations on my free time this weekend.

**Comment by aniel300** [comment]
sounds good. hit me up in discord when u are available.

**Comment by sonroyaalmerol** [comment]
Test the PR if it works for you. That should add a wait time (in seconds) when the retry is triggered.

**Comment by aniel300** [comment]
i was looking more for a rate setting. am assuming `MAX_RETRIES` gets triggered immediately after "x" errors accrue. am assuming `MAX_RETRIES` when it gets triggered it request/ and/or make a new connection back to the provider, am looking to have full control at the speed/rate in seconds at which that happens. i hope i make sense.

**Comment by sonroyaalmerol** [comment]
That's all the control you can get. It's already retrying at full speed by default. The config allows you to add delay. Any more "control" is just plain impossible unless you want the software to control the frequency of your CPU as well. Unless you're able to define anything concrete, I'm merging the PR and closing this issue as is.

**Comment by aniel300** [comment]
what is the backend behavior when `MAX_RETRIES` gets triggered? i just would like to control that behavior at will in seconds without an error being mandatory.

**Comment by sonroyaalmerol** [comment]
The term "retry" already implies means it is triggered on connection failure. How would the proxy know a retry is needed if there's no error? And why would a retry even be needed if there's no error in the first place?

**Comment by aniel300** [comment]
ok I understand, thank you for trying.

**Comment by aniel300** [comment]
this is the issue am trying to fix...here are some logs.
`2024/09/22 05:35:59 Background process: Updated M3U #1 from [redacted url]
2024/09/22 05:35:59 Background process: M3U fetching complete. Saving to database...
2024/09/22 05:35:59 Background process: Updated M3U database.
2024/09/22 05:35:59 CACHE_ON_SYNC enabled. Building cache.
2024/09/22 05:36:12 Received request from 172.18.0.2:33768 for URL: xxx
2024/09/22 05:36:12 Current number of connections for M3U_1: 0
2024/09/22 05:36:12 Proxying 172.18.0.2:33768 to [redacted url]
2024/09/22 05:36:12 Current number of connections for M3U_1: 1
2024/09/22 05:36:13 Received request from 172.18.0.2:33774 for URL: xxx
2024/09/22 05:36:13 Current number of connections for M3U_1: 1
2024/09/22 05:36:14 Proxying 172.18.0.2:33774 to [redacted url]
2024/09/22 05:36:14 Current number of connections for M3U_1: 2
2024/09/22 05:36:15 Stream ended (EOF reached): 172.18.0.2:33768
2024/09/22 05:36:15 Exit code 2 received from [redacted url]
2024/09/22 05:36:15 Retrying other servers...
2024/09/22 05:36:15 Skipping M3U_1: marked as previous stream
2024/09/22 05:36:15 Current number of connections for M3U_1: 1
2024/09/22 05:36:15 Current number of connections for M3U_1: 1
2024/09/22 05:36:16 Proxying 172.18.0.2:33768 to [redacted url]
2024/09/22 05:36:16 Current number of connections for M3U_1: 2
2024/09/22 05:36:18 Stream ended (EOF reached): 172.18.0.2:33774
2024/09/22 05:36:18 Exit code 2 received from [redacted url]
2024/09/22 05:36:18 Retrying other servers...
2024/09/22 05:36:18 Skipping M3U_1: marked as previous stream
2024/09/22 05:36:18 Current number of connections for M3U_1: 1
2024/09/22 05:36:18 Current number of connections for M3U_1: 1
2024/09/22 05:36:18 Proxying 172.18.0.2:33774 to [redacted url]
2024/09/22 05:36:18 Current number of connections for M3U_1: 2
2024/09/22 05:36:23 Context canceled for stream: 172.18.0.2:33774
2024/09/22 05:36:23 Exit code 0 received from [redacted url]
2024/09/22 05:36:23 Client has closed the stream: 172.18.0.2:33774
2024/09/22 05:36:23 Current number of connections for M3U_1: 1
2024/09/22 05:36:24 Context canceled for stream: 172.18.0.2:33768
2024/09/22 05:36:24 Exit code 0 received from [redacted url]
2024/09/22 05:36:24 Client has closed the stream: 172.18.0.2:33768
2024/09/22 05:36:24 Current number of connections for M3U_1: 0
2024/09/22 05:36:24 Client disconnected: 172.18.0.2:33768`

**Comment by sonroyaalmerol** [comment]
Again, "EOF reached" is the server stopping the stream on their end. Reasons can include overloading. This is not a proxy issue.

**Comment by aniel300** [comment]
and there is nothing that can be done in this case to make the stream more robust and stable? like asking for the chunks ahead of time, making a new connection back to the provider, or something else? btw am not saying this is a proxy issue. as it stands right now your proxy is doing wonders.

**Comment by sonroyaalmerol** [comment]
When you're streaming a live video, the proxy and your player already requests chunks ahead of time. These requests happen asynchronously, meaning they don't wait for each other. However, if the server is slow in sending these chunks, it can’t keep up with the speed at which you're watching or listening.

When the proxy runs out of chunks to serve, it tries to reconnect to the provider's server repeatedly until it either gets the next chunk or gives up after a certain number of attempts (`MAX_RETRIES`). Every time it tries again, it makes a fresh request to the server. If the provider's server is stuck or struggling to send one particular chunk, the player keeps getting that same chunk over and over with each retry, causing the content to skip back and replay the same part.

I will see what I can do to improve the buffer system but I cannot promise that this will improve your streams at all. Either way, I'm closing this issue but the buffer improvements will be tracked on #164.
