### ISSUE TITLE
Compatibility issue with IPTVeditor importing VODs as live TV (possibly a stream URL format issue)

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#154]
as discussed in discord: "any plans or does it make sense on supporting `.../stream/...`, `.../movie/...` and `.../series/...` for separating live channels, movies and tv shows at the m3u level?"

**Comment by aniel300** [comment]
can providers also be separated at the m3u level e.g

`.../stream/provider1/...`
`.../movie/provider2/...`
`.../series/provider3/...`
etc

**Comment by sonroyaalmerol** [comment]
Separating providers doesn't make sense to me as the whole point of this project is to merge them.

Also, just for clarification, do you mean generating a separate m3u playlists for each categories based on the original stream urls?

**Comment by aniel300** [comment]
i dont think that is what am after. in the future i would like to be able to choose between exporting live tv, movies and/or tv shows. but for this request i would like to see the ability to to 1: make sure msmp separates lives tv, from movies and tv shows (vod) as right now everything is put into `.../stream/...` and i also would like the ability to separate providers at the m3u level like in this example. https://github.com/sonroyaalmerol/m3u-stream-merger-proxy/issues/154#issuecomment-2320893397

**Comment by sonroyaalmerol** [comment]
Is using the newly implemented include and exclude features (#156) not enough for your use case? I can imagine using that along with having one instance of the proxy per category would work.

I'd need a better reason for me to implement dynamic base paths as it's too cumbersome tbh. The only reasons I would probably consider doing this is if it's to increase compatibility with certain clients.

**Comment by aniel300** [comment]
different instances i dont think it will work. there is two requests in this post. u saying u not implementing either of them. as for a better reason, i was trying to use ur proxy with sm and use his fallback feature but i wanted to distinguish between the different providers at the time of doing the fallback stuff (which is manually) per channel.

**Comment by sonroyaalmerol** [comment]
I see, manually setting fallback options per channel would be difficult to implement without having some sort of web interface. I'll definitely keep that feature in mind and see what I can do. Probably on a separate project as I like to modularize functionalities. But for now, i'll close this as not planned for this specific repo. I'll update you when I've decided to do it.

**Comment by sonroyaalmerol** [comment]
Clarified on discord. Will be using this issue to track the compatibility issue with IPTVeditor importing VODs as live TV instead.

**Comment by sonroyaalmerol** [comment]
Can you check out #160 and see if this feature is enough for your use case?

**Comment by sonroyaalmerol** [comment]
Try out #161 if that works for you @aniel300

**Comment by aniel300** [comment]
it is working now. however, the URL scheme now has `.../proxy/...` as part of it is that intended something like this: `http://xxx/proxy/movie/xxx/xxx/en-a-murder-to-remember-2020.mkv`

**Comment by sonroyaalmerol** [comment]
Yes, that is intentional. There is no such thing as a standard m3u url scheme. Closing issue as resolved

**Comment by aniel300** [comment]
things seems to be working for tv shows but not for movies. it is not updating for some reason.
![image](https://github.com/user-attachments/assets/319dbbec-c9e5-4c03-a4de-b919586c74b7)
![Bluestacks_Md8do97w3P](https://github.com/user-attachments/assets/048cc843-3b34-4611-b438-572af4e2d5be)

**Comment by aniel300** [comment]
i was able to confirm it working using another app. thank u for ur hard work

**Comment by aniel300** [comment]
I just noticed the new url scheme is including the original m3u username and password, is that as designed?

**Comment by sonroyaalmerol** [comment]
Yes, it uses the same base path as the original M3U to avoid any more problems concerning keywords in URLs used to categorize some streams.

**Comment by aniel300** [comment]
umm interesting. this could work for distinguishing different providers but that remains to be seen. I still would like that to be customizable but I will tale this over nothing.
