### ISSUE TITLE
Bug in filter handling

### ISSUE THREAD

**Issue by larsron** [sonroyaalmerol/m3u-stream-merger-proxy#168]
## Describe the bug

There is an error in the GetFilters function in env.go that causes the function to only run for "EXCLUDE_GROUPS" and not for the other filters.

Suggested fix:
The "filtersInitialized = true" must be removed or else all filters except "EXCLUDE_GROUPS" will just return without parsing. Is the test for filtersInitialized even needed in this function as it is set and tested for in the checkFilter function in filters.go?

I have tested the following change to the function and this works as expected:

```go
func GetFilters(baseEnv string) []string {
	if filtersInitialized {
		return filters
	}
	filters = []string{}
	for _, env := range os.Environ() {
		pair := strings.SplitN(env, "=", 2)
		if strings.HasPrefix(pair[0], baseEnv) {
			indexString := strings.TrimPrefix(pair[0], fmt.Sprintf("%s_", baseEnv))
			_, err := strconv.Atoi(indexString)
			if err != nil {
				continue
			}
			filters = append(filters, pair[1])
		}
	}
	// filtersInitialized = true
	return filters
}
```

## To Reproduce

Run with a filter other than "EXCLUDE_GROUPS" configured.

## Expected behavior

Filter the playlist according to the filters configured.

## Actual behavior

All filters except "EXCLUDE_GROUPS" are ignored.

**Comment by sonroyaalmerol** [comment]
The filters variable under the utils package is meant to serve as an in-memory cache. By commenting out `filtersInitialized = true`, you're forcing the function to skip the "cache" every execution.

Given that this function will be executed for every single line in every single M3U file, the cache is necessary. I try to avoid executing nested loops during parsing if it is not necessary for performance reasons.

I don't have any time to test #169 and merge to main right now but feel free to test it if it fixes the issue.

**Comment by larsron** [comment]
Can confirm that #169 fixed the issue for me.
