### ISSUE TITLE
getting some odd behavior with the logs

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#171]
this one is a hard one because idk how or when it happens, i believe it just happens when am changing channels around and why not but hard to tell.  all i know is that the counter gets bug, and the logs gets stuck/spammed. here is a screenshot of how it looks.
![msedge_1P7oP31thh](https://github.com/user-attachments/assets/028a6765-7530-462f-90e4-dc3fe579d548)

**Comment by sonroyaalmerol** [comment]
i'll keep my eye out for this one when i work on other issues. unfortunately, it's hard for me to directly fix a problem if there's no accurate way of recreating it

**Comment by aniel300** [comment]
that is understandable. i think i had debug disabled so i will try to gather more info/ logs by enabling it and hopefully that can give u more insight.

**Comment by aniel300** [comment]
closing for the time being as per https://github.com/sonroyaalmerol/m3u-stream-merger-proxy/issues/173#issuecomment-2403480167

**Comment by aniel300** [comment]
not sure if this is related to this but i keep getting `2024/10/14 05:58:32 Current number of connections for M3U_7: -1` from time to time. unfortunately, am having to have `- SAFE_LOGS=true` otherwise the proxy chucks

**Comment by aniel300** [comment]
re-evaluating (closing for right now)
