### ISSUE TITLE
Video Streams Not Terminating After Viewer Client Is Closed

### ISSUE THREAD

**Issue by jbumgard** [sonroyaalmerol/m3u-stream-merger-proxy#173]
I'm ultimately tryign to setup threadfin to work with this proxy for use with multiple accounts.  However, what i found is that when i connect to one of the streams through the proxy (this service) everything works great until i close the viewer (in this test case i tested both vlc player as well as threadfin).  What i find is that the stream connection is still left open running and is never terminated.  Any help with this issue would be greatly appreciated.

**Comment by jbumgard** [comment]
Additional info
![image](https://github.com/user-attachments/assets/48cd5e5c-a89a-4e42-a32d-e7b70ec15b01)

**Comment by jbumgard** [comment]
Here are some screenshots of the logs, seems like the writing of the response when connection is terminated is failing.  Any ideas?

![image](https://github.com/user-attachments/assets/1afd3f30-5f54-4467-8600-b0a1682cfc77)

**Comment by sonroyaalmerol** [comment]
Which specific line in the log did you terminate the connection on the client side (threadfin and vlc)?

**Comment by aniel300** [comment]
huh 🤔 this might tie into my bw behavior post but not 100% sure https://github.com/sonroyaalmerol/m3u-stream-merger-proxy/issues/172

**Comment by jbumgard** [comment]
SO i spent about 4 hours tonight messing around with this and here is what i found.
Leave threadfin, and jelly fin completly out of the equation.  I used this M3u stream merger proxy and VLC Player.  What i found was that one of the updates done after 0.12.1 has changed the way streams are released.  Even though the newer versions say that the connection has been closed, i'm finding that the stream is still open with my provider.  I started at the latest version and started working backwards, installing each version until i saw the problem go away.  Version 0.12.1 is the last version that seemed to work correctly in regards to actually termnating the actual stream to the provider once the client has been closed.  All newer version would report in the log that the client has been closed but the stream remains open.

**Comment by aniel300** [comment]
wow this is very good find. this might explain why i was getting phantom bw usage. hopefully it is an easy fix.

**Comment by jbumgard** [comment]
got even more info for you now.  So all the m3u stream paths coming from proxy still work fine with vlc player but anytime i try to connect it to threadfin or even directly to jellyfin the streams just sit there and try to buffer and never start.  I started with the latest release and worked my way backwards through every version.   When i reached version 0.7.0 things started working as expected.  When i ran version 0.7.0 i found that the m3u merger proxy works as expected not only with vlc player, but also jellyfin.   I couldn't get any version newer then 0.7.0 to work with jellyfin due to non-stop buffering and streams never starting.

**Comment by aniel300** [comment]
is that last comment related to a different issue?

**Comment by sonroyaalmerol** [comment]
Thanks for your hard work, @jbumgard! i was able to find some things that might fix it. Can you try out the `ghcr.io/sonroyaalmerol/m3u-stream-merger-proxy:pr-174` image and see if that helps? 

Unfortunately, i don't have the right setup to recreate the issue right now so I'm gonna need to rely on you to test it for me.

**Comment by jbumgard** [comment]
Absolutely.  I’m also a developer myself.  I deal with lots of web based rest apis, services, and build full enterprise level apps by day lol.I’ll give it a test when I get some time and I’ll let you know shortly. ThanksJoshuaOn Oct 9, 2024, at 4:41 PM, Son Roy Almerol ***@***.***> wrote:﻿
Thanks for your hard work, @jbumgard! i was able to find some things that might fix it. Can you try out the ghcr.io/sonroyaalmerol/m3u-stream-merger-proxy:pr-174 image and see if that helps?
Unfortunately, i don't have the right setup to recreate the issue right now so I'm gonna need to rely on you to test it for me.

**Comment by aniel300** [comment]
a quick testing shows the issue might have been fixed. thank you @sonroyaalmerol @jbumgard

**Comment by jbumgard** [comment]
Well after much reconfig and testing, @sonroyaalmerol  i believe you hit the nail right on the head.  I believe the update you did fixed all of the issues i was having.  The streams not terminating is now fix.  Also, this udpate seemed to also fix the issue i was having with streams not starting correctly in jellyfin.  Not sure what was up with that but all those issues i reported are all gone with this update.  Thanks for your help with this and i hope to be able to help you more in the future as i intend to use this for a while.

**Comment by aniel300** [comment]
@sonroyaalmerol I still get `2024/10/09 22:10:41 Error writing to response: write tcp 172.18.0.3:8080->172.18.0.2:42752: write: broken pipe` in the logs, is that normal?

**Comment by sonroyaalmerol** [comment]
Yes, it's normal when you're closing a stream. Broken pipe just means the proxy attempted to send a data to a client with its connection already closed.

**Comment by aniel300** [comment]
ok cool and thanks for the explanation

**Comment by aniel300** [comment]
everything seems to be working smoot. aside from the previous explanation u gave me do u see anything wrong with these logs?

2024/10/10 02:19:04 Channel not found from M3U_4: #EXTVLCOPT:network-caching=1000
2024/10/10 02:19:04 Channel not found from M3U_3: #EXTVLCOPT:network-caching=1000
2024/10/10 02:19:04 Channel not found from M3U_2: #EXTVLCOPT:network-caching=1000
2024/10/10 02:19:04 Channel not found from M3U_5: #EXTVLCOPT:network-caching=1000
2024/10/10 02:19:04 Current number of connections for M3U_7: 0
2024/10/10 02:19:34 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:19:34 Channel not found from M3U_9: #EXTVLCOPT:network-caching=1000
2024/10/10 02:19:34 Channel not found from M3U_6: #EXTVLCOPT:network-caching=1000
2024/10/10 02:19:34 Channel not found from M3U_8: #EXTVLCOPT:network-caching=1000
2024/10/10 02:19:34 Current number of connections for M3U_10: 0
2024/10/10 02:20:05 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:20:05 Channel not found from M3U_1: #EXTVLCOPT:network-caching=1000
2024/10/10 02:20:05 Channel not found from M3U_4: #EXTVLCOPT:network-caching=1000
2024/10/10 02:20:05 Channel not found from M3U_3: #EXTVLCOPT:network-caching=1000
2024/10/10 02:20:05 Channel not found from M3U_2: #EXTVLCOPT:network-caching=1000
2024/10/10 02:20:05 Channel not found from M3U_5: #EXTVLCOPT:network-caching=1000
2024/10/10 02:20:05 Current number of connections for M3U_7: 0
2024/10/10 02:20:35 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:20:35 Channel not found from M3U_9: #EXTVLCOPT:network-caching=1000
2024/10/10 02:20:35 Channel not found from M3U_6: #EXTVLCOPT:network-caching=1000
2024/10/10 02:20:35 Channel not found from M3U_8: #EXTVLCOPT:network-caching=1000
2024/10/10 02:20:35 Current number of connections for M3U_10: 0
2024/10/10 02:21:06 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:21:06 Channel not found from M3U_1: #EXTVLCOPT:network-caching=1000
2024/10/10 02:21:06 Channel not found from M3U_4: #EXTVLCOPT:network-caching=1000
2024/10/10 02:21:06 Channel not found from M3U_3: #EXTVLCOPT:network-caching=1000
2024/10/10 02:21:06 Channel not found from M3U_2: #EXTVLCOPT:network-caching=1000
2024/10/10 02:21:06 Channel not found from M3U_5: #EXTVLCOPT:network-caching=1000
2024/10/10 02:21:06 Current number of connections for M3U_7: 0
2024/10/10 02:21:36 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:21:36 Channel not found from M3U_9: #EXTVLCOPT:network-caching=1000
2024/10/10 02:21:36 Channel not found from M3U_6: #EXTVLCOPT:network-caching=1000
2024/10/10 02:21:36 Channel not found from M3U_8: #EXTVLCOPT:network-caching=1000
2024/10/10 02:21:36 Current number of connections for M3U_10: 0
2024/10/10 02:22:07 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:22:07 Channel not found from M3U_1: #EXTVLCOPT:network-caching=1000
2024/10/10 02:22:07 Channel not found from M3U_4: #EXTVLCOPT:network-caching=1000
2024/10/10 02:22:07 Channel not found from M3U_3: #EXTVLCOPT:network-caching=1000
2024/10/10 02:22:07 Channel not found from M3U_2: #EXTVLCOPT:network-caching=1000
2024/10/10 02:22:07 Channel not found from M3U_5: #EXTVLCOPT:network-caching=1000
2024/10/10 02:22:07 Current number of connections for M3U_7: 0
2024/10/10 02:22:37 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:22:37 Channel not found from M3U_9: #EXTVLCOPT:network-caching=1000
2024/10/10 02:22:37 Channel not found from M3U_6: #EXTVLCOPT:network-caching=1000
2024/10/10 02:22:37 Channel not found from M3U_8: #EXTVLCOPT:network-caching=1000
2024/10/10 02:22:37 Current number of connections for M3U_10: 0
2024/10/10 02:23:00 Received request from 172.18.0.2:41350 for URL: /proxy/xxx/24-7-big-mouth.ts
2024/10/10 02:23:00 Current number of connections for M3U_1: 0
2024/10/10 02:23:01 Proxying 172.18.0.2:41350 to https://xxx/391387.ts
2024/10/10 02:23:01 Current number of connections for M3U_1: 1
2024/10/10 02:23:07 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:23:07 Channel not found from M3U_1: #EXTVLCOPT:network-caching=1000
2024/10/10 02:23:07 Channel not found from M3U_4: #EXTVLCOPT:network-caching=1000
2024/10/10 02:23:07 Channel not found from M3U_3: #EXTVLCOPT:network-caching=1000
2024/10/10 02:23:07 Channel not found from M3U_5: #EXTVLCOPT:network-caching=1000
2024/10/10 02:23:07 Channel not found from M3U_2: #EXTVLCOPT:network-caching=1000
2024/10/10 02:23:07 Current number of connections for M3U_7: 0
2024/10/10 02:23:38 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:23:38 Channel not found from M3U_9: #EXTVLCOPT:network-caching=1000
2024/10/10 02:23:38 Channel not found from M3U_6: #EXTVLCOPT:network-caching=1000
2024/10/10 02:23:38 Channel not found from M3U_8: #EXTVLCOPT:network-caching=1000
2024/10/10 02:23:38 Current number of connections for M3U_10: 0
2024/10/10 02:24:04 Received request from 172.18.0.2:42498 for URL: /proxy/xxx/24-7-bojack-horseman.ts
2024/10/10 02:24:04 Channel not found from M3U_4: 24/7: BoJack Horseman
2024/10/10 02:24:04 Current number of connections for M3U_1: 1
2024/10/10 02:24:04 Proxying 172.18.0.2:42498 to https://xxx/391399.ts
2024/10/10 02:24:04 Current number of connections for M3U_1: 2
2024/10/10 02:24:07 Received request from 172.18.0.2:42504 for URL: /proxy/xxx/24-7-disenchantment.ts
2024/10/10 02:24:07 Current number of connections for M3U_1: 2
2024/10/10 02:24:07 Proxying 172.18.0.2:42504 to https://xxx/416024.ts
2024/10/10 02:24:07 Current number of connections for M3U_1: 3
2024/10/10 02:24:08 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:24:08 Channel not found from M3U_1: #EXTVLCOPT:network-caching=1000
2024/10/10 02:24:08 Channel not found from M3U_4: #EXTVLCOPT:network-caching=1000
2024/10/10 02:24:08 Channel not found from M3U_3: #EXTVLCOPT:network-caching=1000
2024/10/10 02:24:08 Channel not found from M3U_5: #EXTVLCOPT:network-caching=1000
2024/10/10 02:24:08 Channel not found from M3U_2: #EXTVLCOPT:network-caching=1000
2024/10/10 02:24:08 Current number of connections for M3U_7: 0
2024/10/10 02:24:10 Received request from 172.18.0.2:35832 for URL: /proxy/xxx/24-7-fugget-about-it.ts
2024/10/10 02:24:10 Channel not found from M3U_4: 24/7: Fugget About It
2024/10/10 02:24:10 Current number of connections for M3U_1: 3
2024/10/10 02:24:10 Proxying 172.18.0.2:35832 to https://xxx/416042.ts
2024/10/10 02:24:10 Current number of connections for M3U_1: 4
2024/10/10 02:24:39 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:24:39 Channel not found from M3U_9: #EXTVLCOPT:network-caching=1000
2024/10/10 02:24:39 Channel not found from M3U_6: #EXTVLCOPT:network-caching=1000
2024/10/10 02:24:39 Channel not found from M3U_8: #EXTVLCOPT:network-caching=1000
2024/10/10 02:24:39 Current number of connections for M3U_10: 0
2024/10/10 02:25:09 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:25:09 Channel not found from M3U_4: #EXTVLCOPT:network-caching=1000
2024/10/10 02:25:09 Channel not found from M3U_1: #EXTVLCOPT:network-caching=1000
2024/10/10 02:25:09 Channel not found from M3U_3: #EXTVLCOPT:network-caching=1000
2024/10/10 02:25:09 Channel not found from M3U_2: #EXTVLCOPT:network-caching=1000
2024/10/10 02:25:09 Channel not found from M3U_5: #EXTVLCOPT:network-caching=1000
2024/10/10 02:25:09 Current number of connections for M3U_7: 0
2024/10/10 02:25:39 Error fetching stream: Get "http://radio.rusradio.fm:24000/;stream.mp3": dial tcp 72.14.187.120:24000: i/o timeout
2024/10/10 02:25:39 Channel not found from M3U_9: #EXTVLCOPT:network-caching=1000
2024/10/10 02:25:39 Channel not found from M3U_6: #EXTVLCOPT:network-caching=1000
2024/10/10 02:25:39 Channel not found from M3U_8: #EXTVLCOPT:network-caching=1000
2024/10/10 02:25:39 Current number of connections for M3U_10: 0

**Comment by sonroyaalmerol** [comment]
This looks like a parser problem caused by an incompatible m3u file. Not related to this issue at all. Please open up a separate issue for this.

**Comment by aniel300** [comment]
will do, thanks.
