### ISSUE TITLE
can u make the proxy/ parser works with these free sources?

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#177]
https://git.gra.phite.ro/frost/repo/raw/branch/main/tv.m3u
https://iptv-org.github.io/iptv/index.m3u
https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8
https://tinyurl.com/tta-m3u
https://raw.githubusercontent.com/dtankdempse/streamed-su-sports/refs/heads/main/vlc_playlist.m3u8
http://bit.ly/FTV-ENG
http://bit.ly/FTV-ESP
http://bit.ly/FTV-ARA

TIA

**Comment by aniel300** [comment]
i think it works but am not sure

**Comment by sonroyaalmerol** [comment]
What exactly is not working?

**Comment by aniel300** [comment]
i thought it was not working. never mind and closing
