### ISSUE TITLE
is there a way to make the proxy works with those streams that send a low quality first and then a higher bitrate one (i think they are called "hls" streams)?

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#179]
is there a way to make the proxy works with those streams that send a low quality first and then a higher bitrate one (i think they are hls ones). i did some testing and smarters and xciptv only play the low bitrate one, tivimate doesn't play it at all. vlc, etc are fine. is there anything that can be done in this case?

**Comment by sonroyaalmerol** [comment]
I did some research and it seems like priority level is not something you can control server side. The server will only announce which stream has which resolution and bitrate. Other than that, the client (e.g. tivimate, vlc, etc.) decides which stream it'll use.

**Comment by aniel300** [comment]
fair enough. closing for now
