### ISSUE TITLE
server is crashing because logs get too big, and server runs out of space.

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#181]
please can u way to either choose the size of the log, rotate it and/or an option to disable logs. here is a screenshot of the logs getting spammed idk why
![image](https://github.com/user-attachments/assets/90576918-ae30-4248-939b-bfb6496e369a)

**Comment by aniel300** [comment]
re-evaluating (closing for right now)

**Comment by aniel300** [comment]
keeps happening 😭

**Comment by sonroyaalmerol** [comment]
Log storage and rotation are all orchestrated by docker and not the container. This is out of this repo's scope. Figure out your own appropriate compose configs.

**Comment by aniel300** [comment]
didnt u when we were ts exporting big m3u enabled extra logs/debug? can u turn that off?
