### ISSUE TITLE
Help regarding INCLUDE and EXCLUDE environmental variables

### ISSUE THREAD

**Issue by dotbanana** [sonroyaalmerol/m3u-stream-merger-proxy#183]
First thanks for this awesome software.  
I got everything working but i have a hard time understanding the INCLUDE and EXCLUDE environmental variables.  

In the documentation it says "Go regexp".  
I assume "regular expression" is meant with that.  
I've tried using a "regex generator" with a list and the GROUP NAME i want to filter but all he gave me was a command only with brackets, not with the GROUP NAME.   
  
Can you please give a working example of what to put inside there so that he filters, for example, all groups that have "WEBCAM" in their name?   

Also why is it structured like so: "INCLUDE_GROUPS_1, INCLUDE_GROUPS_2, INCLUDE_GROUPS_X".  
Is it matching with the "M3U_URL_1, M3U_URL_2, M3U_URL_X" variables?  
So that Filter INCLUDE_GROUPS_1 only matches with M3U_URL_1?  
Or do you have to make a single filter for every matching group you desire?    

Edit:  
Does the new playlist, the one that this program gives out, gets created after every "docker compose down && docker compose up -d" ?
Or does it happen only after sync (meaning here: pull m3u from remote server)?  
Because i have sync_on_boot deactivated exactly for the purpose of tinkering with those filters.  
If it doesn't do anything in this case that would explain why i see basically no results no matter what i input in those fields.  I've tried everything i can think of by now.  
Is this feature even functional?

**Comment by sonroyaalmerol** [comment]
> In the documentation it says "Go regexp". I assume "regular expression" is meant with that.

Yes, this is correct.
 
> Can you please give a working example of what to put inside there so that he filters, for example, all groups that have "WEBCAM" in their name?

Regular expressions do seem complicated but if you only need to use a static set of characters for the filter, you can simply use that as is. In this case, you can just use: `INCLUDE_GROUPS_1=WEBCAM` as an example.

> Also why is it structured like so: "INCLUDE_GROUPS_1, INCLUDE_GROUPS_2, INCLUDE_GROUPS_X". Is it matching with the "M3U_URL_1, M3U_URL_2, M3U_URL_X" variables? So that Filter INCLUDE_GROUPS_1 only matches with M3U_URL_1? Or do you have to make a single filter for every matching group you desire?

I can see how this is confusing. Sorry for the lack of documentation. They aren't meant to match with the M3U numerical assignments. They're simply there if you needed to use multiple regexp filters.

For example, if you need to include groups with "WEBCAM" and "TV", you can set `INCLUDE_GROUPS_1=WEBCAM` and `INCLUDE_GROUPS_2=TV`. You can also achieve the same result if you merge the two filters into one regexp with `INCLUDE_GROUPS_1=WEBCAM|TV`.

> Edit: Does the new playlist, the one that this program gives out, gets created after every "docker compose down && docker compose up -d" ? Or does it happen only after sync (meaning here: pull m3u from remote server)?

Filters are applied during the parsing of the M3Us. The parsing process only happens once after downloading the original M3Us from its sources so you'll need the sync to trigger for the filters to be applied.

**Comment by dotbanana** [comment]
> Filters are applied during the parsing of the M3Us. The parsing process only happens once after downloading the original M3Us from its sources so you'll need the sync to trigger for the filters to be applied.

Ohh, okay.   
This explains everything. :)  
Thanks a lot for your time!
