### ISSUE TITLE
URL's too long for VLC

### ISSUE THREAD

**Issue by kp-emagine** [sonroyaalmerol/m3u-stream-merger-proxy#191]
Looks like the new URL structure for `Stream Endpoint` is now too long even for VLC to play most streams.

Any chance you can shorten them up?

**Comment by sonroyaalmerol** [comment]
How long is the character limit for VLC?

**Comment by kp-emagine** [comment]
> How long is the character limit for VLC?

Unfortunately, I do not know.  All I know is most of my streams would not play.  Streams that I know work.  Nothing really in the logs either other than `Error reloading stream` either.

**Comment by sonroyaalmerol** [comment]
All good! I'll get back to this asap. You can revert back to the previous version for now

**Comment by kp-emagine** [comment]
Testing now, on creation tho: `Error indexing stream:  (#2) -> open /m3u-proxy/data/streams/_1: no such file or directory`
 Streams still do not play, but there is nothing logged when attempting to play this time.

**Comment by sonroyaalmerol** [comment]
My bad, misplaced some parts of the code. Can you try it again?

**Comment by kp-emagine** [comment]
same. Except that error is changed to: `Error indexing stream: CHANNEL NAME (#x) -> open /m3u-proxy/data/streams/RANDSTRING: no such file or directory
`

**Comment by sonroyaalmerol** [comment]
I forgot that I manually created the directories in my tests. Hopefully, it should be fine now.

**Comment by kp-emagine** [comment]
:)
Now there's logging for it :)  All channels pop the following... URL changes for it each "channel" tho
```
2024/11/18 14:52:42 Received request from MY_CONTAINER_IP:53102 for URL: /p/eadd2279d1/d340f197a9/KLUv_QQA8QEAeyJ0aXRsZSI6IkJFVCIsInR2Z19pZCI6IiIsInR2Z19jaCI6IjYxIiwibG9nbyI6IiIsImdyb3VwIjoiIn1xrJl5
2024/11/18 14:52:42 http: panic serving MY_CONTAINER_IP:53102: assignment to entry in nil map
goroutine 175 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1947 +0xbe
panic({0x7a1680?, 0x8a7480?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
m3u-stream-merger/store.ParseStreamInfoBySlug({0xc00022013d?, 0xc0001687a8?})
	/app/store/parser.go:40 +0x1e5
m3u-stream-merger/store.GetStreamBySlug({0xc00022013d?, 0xad?})
	/app/store/streams.go:12 +0x45
m3u-stream-merger/proxy.NewStreamInstance({0xc00022013d?, 0x64?}, 0xc0000a4140)
	/app/proxy/load_balancer.go:21 +0x5a
m3u-stream-merger/handlers.StreamHandler({0x8aab68, 0xc0004fc1c0}, 0xc0004ba280, 0xc0000a4140)
	/app/handlers/stream_handler.go:29 +0x217
main.main.func2({0x8aab68?, 0xc0004fc1c0?}, 0xc000168b38?)
	/app/main.go:43 +0x25
net/http.HandlerFunc.ServeHTTP(0xaffca0?, {0x8aab68?, 0xc0004fc1c0?}, 0x65d056?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
net/http.(*ServeMux).ServeHTTP(0x465459?, {0x8aab68, 0xc0004fc1c0}, 0xc0004ba280)
	/usr/local/go/src/net/http/server.go:2747 +0x1ca
net/http.serverHandler.ServeHTTP({0xc0005685d0?}, {0x8aab68?, 0xc0004fc1c0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc00017c5a0, {0x8ab6a8, 0xc0000c1080})
	/usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3360 +0x485
```

**Comment by sonroyaalmerol** [comment]
Okay, that should be the last of it unless I missed another thing again 🤦

**Comment by kp-emagine** [comment]
There we go :)
Workin good mate :)

**Comment by sonroyaalmerol** [comment]
It shouldn't. Create a new issue if it does for you
