### ISSUE TITLE
ability to turn off `STREAM_TIMEOUT`

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#201]
am getting `2024/12/15 22:13:14 Retrying same stream until timeout (3 seconds) is reached...` if i try setting it to 1 sec which is the minimum then i get high cpu usage. is there a way to turn this feature off as i don't want it to wait 3 second instead i want it retying the same stream constantly

**Comment by sonroyaalmerol** [comment]
The retry loop getting executed very fast indefinitely is exactly the reason you're getting a high cpu usage.

**Comment by sonroyaalmerol** [comment]
This "feature" has always been here. Otherwise, the exact problem you're having happens. The only "feature" I added was the ability to modify the timeout. Your "solution" is literally the cause of your issue.

**Comment by aniel300** [comment]
lol yeah. so that is a no to revert back?

**Comment by sonroyaalmerol** [comment]
There is nothing to revert. Set it to 0 all you want and that's "turning off" the `STREAM_TIMEOUT`. #140

**Comment by aniel300** [comment]
if i do that then there is high cpu usage if am not mistaken

**Comment by sonroyaalmerol** [comment]
Lower timeout = Higher number of retries
Higher number of retries = Higher CPU usage

Given this data, what do you think will happen if there is no timeout?

There is a reason why I never allowed `STREAM_TIMEOUT` to be set to 0 prior to #140.

Having an endless loop without a timeout in a program is like telling someone to keep running in circles non-stop. They’re not allowed to rest, slow down, or even think—they just keep going at full speed. That’s your CPU in this case, working flat out for no good reason. If you let it take a breather between laps, it wouldn’t be so exhausted (or in this case, stuck at abnormally high CPU usage).

**Comment by aniel300** [comment]
ok now i understand. sorry for my ignorance. and thank u for the explanation
