### ISSUE TITLE
Request - Ability to specify exact sync times instead of timed intervals.

### ISSUE THREAD

**Issue by shorty789** [sonroyaalmerol/m3u-stream-merger-proxy#25]
As above, this is a request to specify the exact time that playlists update, this will allow updates to be tightly scheduled. Using the cron format may allow additional customization, however I have requested this with updating at a specific time every day in mind.

**Comment by sonroyaalmerol** [comment]
Would a cron schedule be sufficient for you?

**Comment by shorty789** [comment]
being able to pass a cron schedule as an env var would be a great addition to be honest.

**Comment by sonroyaalmerol** [comment]
See current dev build. Cron schedule can now be set with the `SYNC_CRON` env var and deprecated `UPDATE_INTERVAL`. Also see `TZ` and `SYNC_ON_BOOT` as they're related to `SYNC_CRON`. Everything should be on the README.
