### ISSUE TITLE
Issue - Playlist selection currently cycles in reverse order

### ISSUE THREAD

**Issue by shorty789** [sonroyaalmerol/m3u-stream-merger-proxy#26]
During testing of the dev build, I can see that the playlists are currently being cycled in reverse order, IE. 4, 3, 2, 1. Please can this be rectified?

Thanks very much.

**Comment by sonroyaalmerol** [comment]
Do you mind testing the current dev build to see if this has been resolved?

**Comment by shorty789** [comment]
This does seem to be resolved now based on the testing I have done over the last couple of days. Thank you very much!
