### ISSUE TITLE
Using Development build - Encountered this error.

### ISSUE THREAD

**Issue by shorty789** [sonroyaalmerol/m3u-stream-merger-proxy#32]
One thing that looks abnormal to me is the 4th line from the bottom seems much longer than all the others.

After encountering this issue, playback completely stopped until i deleted data and recreated the container.

2024/03/11 20:56:40 Error copying MP4 stream to response: read tcp :49528->:8080: use of closed network connection
2024/03/11 20:56:40 Closed connection for :43244
2024/03/11 20:57:07 Received request from :41782 for URL: /stream/VVNBIC0gSUdOIFRWIEhE.mp4
2024/03/11 20:57:07 Current concurrent connections for M3U_1: 1
2024/03/11 20:57:07 Concurrency limit reached (1): http://
2024/03/11 20:57:07 Current concurrent connections for M3U_2: 0
2024/03/11 20:57:32 Received request from :43790 for URL: /stream/VVNBIC0gSUdOIFRWIEhE.mp4
2024/03/11 20:57:32 Current concurrent connections for M3U_1: 1
2024/03/11 20:57:32 Concurrency limit reached (1): http://
2024/03/11 20:57:32 Current concurrent connections for M3U_2: 0
2024/03/11 20:57:37 Error fetching MP4 stream (concurrency check mode): Get "http:///offline.ts": dial tcp :80: i/o timeout
2024/03/11 20:57:37 Current concurrent connections for M3U_3: 0
2024/03/11 20:58:07 Error fetching MP4 stream (concurrency check mode): Get "http:///offline.ts": dial tcp :80: i/o timeout
2024/03/11 20:58:07 Current concurrent connections for M3U_4: 0
2024/03/11 20:58:08 Proxying :43790 to http://
2024/03/11 20:58:08 Sent MP4 stream to :43790
2024/03/11 20:58:08 Current concurrent connections for M3U_2: 1
2024/03/11 20:58:08 Client disconnected after fetching MP4 stream
2024/03/11 20:58:08 Error copying MP4 stream to response: write tcp :8080->:43790: write: connection reset by peer
2024/03/11 20:58:08 Closed connection for :43790
2024/03/11 20:58:08 Current concurrent connections for M3U_2: 0
2024/03/11 20:58:33 Received request from :56386 for URL: /stream/RCsgKFVLKSBFdmVudHMgNTk6IEJpYXRobG9uIHwgU29sZGllciBIb2xsb3cgfCBXb21lbmBzIFB1cnN1aXQgfCBXb3JsZCBDdXAgfCBTdW4gMTAgTWFyIDE2OjQ1.mp4
2024/03/11 20:58:33 Current concurrent connections for M3U_1: 1
2024/03/11 20:58:33 Concurrency limit reached (1): http://
2024/03/11 20:58:33 Current concurrent connections for M3U_4: 0

**Comment by sonroyaalmerol** [comment]
The long mp4 string suggests a parsing error. Does the problem persist even after recreating the container? Does it only happen on specific channels?

**Comment by shorty789** [comment]
It seems ok again since deleting the data and recreating the container. It had been running since saturday and at some points had streamed smoothly for 8+ hours, There hasnt been a specific pattern regarding channels either.

**Comment by sonroyaalmerol** [comment]
I can't seem to recreate this issue. I'll leave this one open and let me know if this happens again. I can't really fix an issue without knowing what exactly is triggering it.

**Comment by shorty789** [comment]
No problem I will do, when it happened I was watching a stream no problem at all, then it went to a black screen, it was after attempting to load the channel back up that it tried to load the long string.

I have just encountered another problem that I am planning to try and capture a bit better after a rebuild and further testing, I do not know if they may be related, but I was watching a rather choppy stream, it kept disconnecting, after a while I noticed the same stream was apparently occupying 3/4 of my playlists. I think the concurrency counter doesnt necessarily clear up after disconnecting in such a manner, the client ends up just trying to connect again and ends up moving over to a different playlist. I will let you know when I have some more info.

**Comment by sonroyaalmerol** [comment]
I added a `BUFFER_MB` env var in both dev and latest release. You may try and play around with that for choppy streams. I would suggest using low buffer sizes (maybe 1 or 2).

**Comment by sonroyaalmerol** [comment]
I might've found the issue. I'm guessing both issues might have something to do with connections never timing out even if it's not receiving any response/data. Apparently, this is the default behavior of Go's HTTP client.

I've specified a timeout for the HTTP connections and should disconnect and decrease the concurrency counter as soon as that time has been reached. The fix should be on the `dev` tag.

Let me know if the problem persists.

**Comment by shorty789** [comment]
Seems like its just throwing me off after 10 seconds at the moment

**Comment by sonroyaalmerol** [comment]
> Seems like its just throwing me off after 10 seconds at the moment

My bad. It seems like it forcibly stops long-lived connections this way. I'm reverting it for now until I find a better solution. Should be deployed back to `dev` now.

The buffer feature might help. You can try that for now.

**Comment by sonroyaalmerol** [comment]
I've implemented a _very_ experimental fix in the `:dev` build.

Let me know how it goes. In case the problem gets worse, you can revert back to the `:latest` build.

**Comment by sonroyaalmerol** [comment]
Hi. Do you mind trying the `:dev` image? I've pushed some changes to the algorithm. I'm unable to test things myself as I currently don't have any IPTV subscription. I'm only relying on my automated tests at this point.

**Comment by shorty789** [comment]
initially it seemed to be working OK, but upon the first disconnect, my logs got repeatedly spammed:

2024/07/19 13:40:14 Client disconnected: :50662
2024/07/19 13:40:14 Client disconnected: :50662
2024/07/19 13:40:14 Client disconnected: :50662
2024/07/19 13:40:14 Client disconnected: :50662
2024/07/19 13:40:14 Client disconnected: :50662
2024/07/19 13:40:14 Client disconnected: :50662

There was an extremely high number of these entries.

**Comment by sonroyaalmerol** [comment]
Sorry about that, missed a buggy line leading to an endless loop. Should be going past that loop after disconnecting now. Try pulling the dev image again.

**Comment by shorty789** [comment]
This is what im getting now, currently doesnt seem to be checking the next playlist in the sequence.

2024/07/20 13:49:10 Background process: Updated M3U database.
2024/07/20 13:50:42 Received request from :49338 for URL: /stream/VUsgLSBJVFYgMiBGSEQ=
2024/07/20 13:50:42 Current number of connections for M3U_2: 0
2024/07/20 13:50:43 Proxying :49338 to http://
2024/07/20 13:50:43 Current number of connections for M3U_2: 1
2024/07/20 13:56:02 Received request from :41010 for URL: /stream/VUsgLSBZRVNURVJEQVkrMQ==
2024/07/20 13:56:02 Current number of connections for M3U_2: 1
2024/07/20 13:56:02 Concurrency limit reached for M3U_2: http://
2024/07/20 13:56:02 All concurrency limits have been reached. Falling back to connection checking mode...
2024/07/20 13:56:08 Proxying :41010 to http://
2024/07/20 13:56:08 Current number of connections for M3U_2: 2
2024/07/20 13:56:08 Stream ended (EOF reached): :41010
2024/07/20 13:56:08 Current number of connections for M3U_2: 1
2024/07/20 13:56:08 Server connection failed: http://
2024/07/20 13:56:08 Retrying other servers...
2024/07/20 13:56:08 Current number of connections for M3U_2: 1
2024/07/20 13:56:08 Concurrency limit reached for M3U_2: http://
2024/07/20 13:56:08 All concurrency limits have been reached. Falling back to connection checking mode...
2024/07/20 13:56:13 Reconnected to http://
2024/07/20 13:56:13 Current number of connections for M3U_2: 2
2024/07/20 13:56:13 Stream ended (EOF reached): :41010
2024/07/20 13:56:13 Current number of connections for M3U_2: 1
2024/07/20 13:56:13 Server connection failed: http://
2024/07/20 13:56:13 Retrying other servers...
2024/07/20 13:56:13 Current number of connections for M3U_2: 1
2024/07/20 13:56:13 Concurrency limit reached for M3U_2: http://
2024/07/20 13:56:13 All concurrency limits have been reached. Falling back to connection checking mode...
2024/07/20 13:56:18 Reconnected to http://
2024/07/20 13:56:18 Current number of connections for M3U_2: 2
2024/07/20 13:56:18 Error writing to response: http: wrote more than the declared Content-Length
2024/07/20 13:56:18 Current number of connections for M3U_2: 1
2024/07/20 13:56:18 Client has closed the stream: :41010
2024/07/20 13:56:18 Client disconnected: :41010

**Comment by sonroyaalmerol** [comment]
hi @shorty789, do you mind trying out the latest dev build? as mentioned in the other issue (#64), i'll be focusing on one load balancing mode instead to simplify things. The LB should now sort the streams by the number of "free slots" based on the set concurrency values then do the good old "brute-force" loop.

**Comment by shorty789** [comment]
Heya, seems that it isnt working as expected at the moment. it doesnt seem to hop over to the next playlist as expected, the first stream was fine.

2024/08/11 13:41:31 Received request from :57732 for URL: /stream/VUsgLSBJVFYgNCBVSEQ=
2024/08/11 13:41:31 Current number of connections for M3U_2: 0
2024/08/11 13:41:32 Proxying :57732 to http://
2024/08/11 13:41:32 Current number of connections for M3U_2: 1
2024/08/11 14:04:12 Error writing to response: write tcp :8080->:57732: write: connection reset by peer
2024/08/11 14:04:12 Current number of connections for M3U_2: 0
2024/08/11 14:04:12 Exit code 0 received from http://
2024/08/11 14:04:12 Client has closed the stream: :57732
2024/08/11 14:04:12 Client disconnected: :57732
2024/08/11 14:04:30 Received request from :35880 for URL: /stream/VUsgLSBNVFYgRkhE
2024/08/11 14:04:30 Current number of connections for M3U_2: 0
2024/08/11 14:04:31 Proxying :35880 to http://
2024/08/11 14:04:31 Current number of connections for M3U_2: 1
2024/08/11 14:05:00 Received request from :42234 for URL: /stream/VUsgLSBJVFYgNCBVSEQ=
2024/08/11 14:05:00 Current number of connections for M3U_2: 1
2024/08/11 14:05:00 Concurrency limit reached for M3U_2: http://
2024/08/11 14:05:00 Current number of connections for M3U_2: 1
2024/08/11 14:05:00 Concurrency limit reached for M3U_2: http://
2024/08/11 14:05:00 Current number of connections for M3U_2: 1
2024/08/11 14:05:00 Concurrency limit reached for M3U_2: http://
2024/08/11 14:05:00 Current number of connections for M3U_2: 1
2024/08/11 14:05:00 Concurrency limit reached for M3U_2: http://
2024/08/11 14:05:00 Current number of connections for M3U_2: 1
2024/08/11 14:05:00 Concurrency limit reached for M3U_2: http://
2024/08/11 14:05:00 Current number of connections for M3U_2: 1
2024/08/11 14:05:00 Concurrency limit reached for M3U_2: http://
2024/08/11 14:05:04 Received request from :39584 for URL: /stream/VUsgLSBJVFYgNCBVSEQ=
2024/08/11 14:05:04 Current number of connections for M3U_2: 1
2024/08/11 14:05:04 Concurrency limit reached for M3U_2: http://
2024/08/11 14:05:04 Current number of connections for M3U_2: 1
2024/08/11 14:05:04 Concurrency limit reached for M3U_2: http://
2024/08/11 14:05:04 Current number of connections for M3U_2: 1
2024/08/11 14:05:04 Concurrency limit reached for M3U_2: http://
2024/08/11 14:05:04 Current number of connections for M3U_2: 1
2024/08/11 14:05:04 Concurrency limit reached for M3U_2: http://
2024/08/11 14:05:04 Current number of connections for M3U_2: 1
2024/08/11 14:05:04 Concurrency limit reached for M3U_2: http://
2024/08/11 14:05:04 Current number of connections for M3U_2: 1
2024/08/11 14:05:04 Concurrency limit reached for M3U_2: http://

**Comment by sonroyaalmerol** [comment]
The looping issue is currently being tracked here #84

**Comment by sonroyaalmerol** [comment]
Closing as the initial issue should not be applicable in the latest release at this point. Feel free to reopen otherwise.
