### ISSUE TITLE
Just updated. Error across :latest & :dev

### ISSUE THREAD

**Issue by shorty789** [sonroyaalmerol/m3u-stream-merger-proxy#48]
Hi, I now receive this when I launch the container, this happens on both the latest, and dev version.

exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory
exec /gomain: no such file or directory

**Comment by sonroyaalmerol** [comment]
Sorry about that. Should be fixed in `:dev`. Should also be fixed in `:latest` as soon as it's done building.
