### ISSUE TITLE
Not categorized as live channel

### ISSUE THREAD

**Issue by andjos** [sonroyaalmerol/m3u-stream-merger-proxy#60]
## Describe the bug
In players like implayer stream not categorized as live channel, but as vod.

## To Reproduce

1. Tested with implayer for Android.

## Expected behavior
Live channels and vod should be in right category

## Additional context
in v0.7.1 tested to remove .mp4 extension of stream, this make implayer to work.

**Comment by sonroyaalmerol** [comment]
There is a `#EXT-X-PLAYLIST-TYPE` EXT tag (which applies to the entire playlist) that indicates the type of playlist, such as "VOD" (video on demand) or "EVENT". Without that tag, the playlist should be considered as a playlist of live channels by default.

There is nothing in the M3U/IPTV standard (that I know of) that allows a client to categorize each stream, whether it's a VOD or a Live channel, individually.

But, I don't know how implayer checks its categories, so let's start from there. What you can try is to load up an M3U that is known to categorize correctly in implayer. Then, compare the tags between the working M3U and the proxy M3U and identify which tags are missing in the proxy M3U. 

Let me know if you found the tags required so I can add them to the parser.

**Comment by andjos** [comment]
This file [https://iptv-org.github.io/iptv/languages/swe.m3u](url) loads ok in implayer and Perfect IPTV player. Parsing same playlist gives no found channels. Cant find any special tag. 
Looking at a m3u file from a provider that provides booth live channels and VOD, all VOD files has some type of extension like .mkv, .mp4 but live channels have nothing..

**Comment by sonroyaalmerol** [comment]
I just merged PR 61. The M3U generator should now follow the source M3U's file extensions. Can you try it with the `:dev` build?

**Comment by andjos** [comment]
Tested `:dev` build, now works in my players.
