### ISSUE TITLE
Suggestion, also maybe a possible fix for connection hanging.

### ISSUE THREAD

**Issue by shorty789** [sonroyaalmerol/m3u-stream-merger-proxy#63]
Given the current issue where the active connections don't always close properly. I can remember something about there being difficulty detecting when a stream has incorrectly terminated. I have mostly just been resetting the container when it happens too much to continue streaming.

When it does happen however and the connection does close, Threadfin produces a log of the error.

I have been wondering if there is any way of using this log information to correctly clear a specific connection from the concurrency counter.

While not the most ideal solution and more of a workaround, it would at least work for those of us who pair this with threadfin.

**Comment by sonroyaalmerol** [comment]
Hi! I personally don't use this anymore so it's been a while since I've revisited this project. But, I'll try and take a look at it this weekend.

**Comment by sonroyaalmerol** [comment]
Now that I had some time, I'm closing this issue in favor of your original issue #32. Fixing the root of the problem should be the focus. Using logs from another service would be problematic and hard for me to maintain. Log messages can differ from one version of Threadfin to another.
