### ISSUE TITLE
Round robin LB doesnt seem to work as expected.

### ISSUE THREAD

**Issue by shorty789** [sonroyaalmerol/m3u-stream-merger-proxy#64]
Hi, as you can see from the logs below, the round robin load balancing method doesnt seem to work as expected, and instead it attempts to load from the same playlist. This wasnt an issue using brute force and concurrency limitations.

2024/07/18 10:12:25 Received request from :43594 for URL: /stream/VUsgLSBDT01FRFkgQ0VOVFJBTCBGSEQ=
2024/07/18 10:12:25 Current number of connections for M3U_3: 0
2024/07/18 10:12:26 Proxying :43594 to http://
2024/07/18 10:12:26 Sent stream to :43594
2024/07/18 10:12:26 Current number of connections for M3U_3: 1
2024/07/18 10:18:39 Received request from :60146 for URL: /stream/VUsgLSBEQVZFIEZIRA==
2024/07/18 10:18:39 Current number of connections for M3U_3: 1
2024/07/18 10:18:39 Concurrency limit reached for M3U_3 (max: 1): http://
2024/07/18 10:18:39 All concurrency limits have been reached. Falling back to connection checking mode...
2024/07/18 10:18:40 Proxying :60146 to http://
2024/07/18 10:18:40 Sent stream to :60146
2024/07/18 10:18:40 Current number of connections for M3U_3: 2
2024/07/18 10:19:10 Error reading stream: EOF
2024/07/18 10:19:10 Closing (:43594) connection.
2024/07/18 10:19:10 Client (:43594) disconnected.
2024/07/18 10:19:10 Current number of connections for M3U_3: 1

**Comment by sonroyaalmerol** [comment]
I've pushed some changes to the `:dev` build that might indirectly fix this.

**Comment by sonroyaalmerol** [comment]
decided to remove the option for different load balancing modes in favor of an optimized default
