### ISSUE TITLE
proxy spits out random channel order

### ISSUE THREAD

**Issue by blackwhitebear8** [sonroyaalmerol/m3u-stream-merger-proxy#67]
## Describe the bug

I have 2 identical m3u inputs with a custom channel order from xteve both inputs are identical but the proxy still manages to reorder them for some reason and now in plex some channels with number id 2 are after number id 40 for example even tho they are numbered as 2.

setup 2 xteve instances with identical channels and numbering and names. and feed both into the proxy. 

## Expected behavior

channel order should be kept 1 to how many channels you have.

## Actual behavior

channel id 1 is after channel id 40 and some other channels are randomly placed.

## Screenshots

![Screenshot from 2024-07-30 19-24-52](https://github.com/user-attachments/assets/7ea50b36-f5d6-487c-99a7-98fbbbaaab53)
![Screenshot from 2024-07-30 19-25-17](https://github.com/user-attachments/assets/620a854a-c548-4544-b061-7370bbf89575)
you can see whats in xteve and the second screenshot shows output of the m3u from the proxy with everything in a different order.

## docker-compose.yml contents

i m using unraid here:
![Screenshot from 2024-07-30 19-26-52](https://github.com/user-attachments/assets/97cd882c-ef85-4479-a86f-c5ad474e0e8c)

## Container/Host Logs

no errors or things just normal operation

**Comment by shorty789** [comment]
I found it to be more effective to place the m3u proxy first, and then feed output into Threadfin (an updated fork of xTeve) before setting a tuner limit. The mapping feature within threadfin/xteve can then reorder the playlist as expected and ensure consistency between endpoints.

as a separate note i found it very important to use both the -re flag, as well reencode the audio as mp3 for streams to work correctly within plex, both of these are done in the ffmpeg options within xteve/threadfin. otherwise they would frequently cut off after a short period of time.

**Comment by blackwhitebear8** [comment]
i tried this aswell but then the proxy would be spitting errors out for hours. so i skipped that idea

**Comment by blackwhitebear8** [comment]
I have forked this repo and editted the code to add the numbers and that works now emby can see them :p but still need to figure out how to get it to generate the m3u in order.

**Comment by sonroyaalmerol** [comment]
> i tried this aswell but then the proxy would be spitting errors out for a min and than crashes. so i skipped that idea
> 
> something with: `goroutine 125334 gp=0xc042b63340 m=nil [runnable]: runtime.cgocall(0x6c93a0, 0xc0421fd7f0) /usr/local/go/src/runtime/cgocall.go:157 ...

this can probably be solved by deleting the existing .db files in the data folder if a persistent volume was mounted. something might've happened which caused things to go out of sync for some reason.

either way, i believe you've found a method that works for you and the issue should be closed by #68
