### ISSUE TITLE
Allow Local M3U Files

### ISSUE THREAD

**Issue by kp-emagine** [sonroyaalmerol/m3u-stream-merger-proxy#78]
**Is your feature request related to a problem? Please describe.**
Unable to pass file://

**Describe the solution you'd like**
Would like to be able to attach a volume to the container, and pass local m3u files to it for processing, for example:
- M3U_URL_1=file:///playlists/mine.m3u

Where /playlists is mapped locally

**Comment by aniel300** [comment]
this feature would be awesome as well

**Comment by kpirnie** [comment]
I know nothing about GoLang... but... this may work in the `downloadM3UToBuffer` method
```
// add right above: // Download M3U for processing live
// if the url string contains file://
	if strings.Contains( m3uURL, "file://" ) {

		// try to open the file
		file, err := os.Open( m3uURL )
		if err != nil {
			return fmt.Errorf("OPEN FILE error: %v", err)
		}
		defer file.Close( )

		// read it in chunks
		for {
			bytesread, err := file.Read( buffer )

			if err != nil {
				if err != io.EOF {
					return fmt.Errorf("END OF FILE: %v", err)
				}

				break
			}

		}

	}
```

**Comment by kpirnie** [comment]
> I know nothing about GoLang... but... this may work in the `downloadM3UToBuffer` method
> 
> ```
> // add right above: // Download M3U for processing live
> ```

mmm.. maybe not, like I said tho, I dont know anything about Go lolol

**Comment by aniel300** [comment]
I least u are trying which is what matters

**Comment by kpirnie** [comment]
> I least u are trying which is what matters
:)  I'll give it another do later on.  =)
Appreciate it

**Comment by sonroyaalmerol** [comment]
Feature support has been merged on the latest dev build. Feel free to reopen if it does not work as expected

**Comment by aniel300** [comment]
> Feature support has been merged on the latest dev build. Feel free to reopen if it does not work as expected

i don't have a use case for this now but i know i might in the future. did u added this to the wiki/ readme?

**Comment by kpirnie** [comment]
Not working on :latest Docker

```
2024/08/20 08:08:51 Downloading M3U from URL: file:///playlists/kp-shows.m3u
2024/08/20 08:08:51 downloadM3UToBuffer error. Retrying in 5 secs... (error: HTTP GET error: Get "file:///playlists/kp-shows.m3u": unsupported protocol scheme "file")
```

Path exists in container
![Screenshot_1](https://github.com/user-attachments/assets/b3015ebc-3486-422a-9892-877e28ee38be)

**Comment by kpirnie** [comment]
> I haven't released it yet. The dev build is accessible with the `:dev` image tag.
Tried hitting you up on Discord... attempting to help look into a couple things ;) (like the above), but can't get a local environment going... apparently WSL doesn't like Redis or something....
