### ISSUE TITLE
new version breaks sorting again

### ISSUE THREAD

**Issue by blackwhitebear8** [sonroyaalmerol/m3u-stream-merger-proxy#82]
V0.11.2 breaks sorting again every channel is once again in a random order.

**Comment by sonroyaalmerol** [comment]
Yes, i'm aware of the issue. This should be fixed in the latest dev build if you don't mind testing.

**Comment by blackwhitebear8** [comment]
i m gona test that one

another issues i guess i put my direct iptv streams in there this time its able to parse them without errors but the playlist.m3u stays empty with this in the logs:

2024/08/18 20:22:31 GetStreams error: stream not found: USA
2024/08/18 20:22:48 GetStreams error: stream not found: USA

prop getting confused with VOD?

**Comment by sonroyaalmerol** [comment]
Might also be because of my previous implementation of the sorting which basically required all lines to have the tvg-id value or else it won't be fetched from the redis db when generating the m3u. If so, then this has been fixed in the latest dev build as well.

**Comment by blackwhitebear8** [comment]
I have now tried the internal m3u from xteve but it aswell stays empty and redis is pulling up to 1GB of memory usage.

it says this in logs: 2024/08/18 20:28:45 GetStreams error: stream not found: #UNFIT

**Comment by blackwhitebear8** [comment]
i have restarted redis in between testing to clear out its memory

**Comment by blackwhitebear8** [comment]
tvg-id seems to be names in there and not numbers

**Comment by sonroyaalmerol** [comment]
I've optimized the redis queries in the dev build just now. Can you try it for me?

**Comment by sonroyaalmerol** [comment]
Closing this issue since I wasn't able to recreate the problem since the recent updates. Feel free to reopen if it is still applicable on the latest release.

**Comment by blackwhitebear8** [comment]
Just upgradd to the latest release. and lets say my channel list starts with 49 and so on 😂 
![image](https://github.com/user-attachments/assets/2cf4c9d6-da94-42a6-b094-53a7c3a45aed)

**Comment by blackwhitebear8** [comment]
idk about toher software but for emby the order in the m3u is used and the ids but the order in the m3u matters more.

**Comment by sonroyaalmerol** [comment]
The screenshot helps. I'll fix it on the next release

**Comment by sonroyaalmerol** [comment]
Hi! Can you test this PR if it works for you? #111 You can use the image URL provided in the PR for your convenience.

**Comment by blackwhitebear8** [comment]
that one seems to work.
![image](https://github.com/user-attachments/assets/627b147a-d32b-4d97-9541-aa1f6795119a)

**Comment by sonroyaalmerol** [comment]
Nice. I'll merge it on the dev build then. Thanks!

**Comment by blackwhitebear8** [comment]
it also now seems to be able to parse the direct m3u from my provider but loading the playlist.m3u is slowly generating the output live? can this be predone and than saved?

**Comment by sonroyaalmerol** [comment]
It should be cached directly to your machine's memory after the first complete generation. Consequent requests after that will use that cache. Any mutation (add, edit, delete, etc.) in the database will clear out that cache. If you want an actual .m3u file, then you can save it yourself from the browser and it will work as per usual.

If it is not working as expected, please open up a separate issue for it. Thanks!
