### ISSUE TITLE
any way to fix this?/ can u add a retry option for channels fails?

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#98]
2024/08/23 21:54:34 [DEBUG] Successfully fetched stream from http://xxx/06d998976b/7822876eecd7/45619
2024/08/23 21:54:34 [DEBUG] Headers set for response: map[Access-Control-Allow-Origin:[*] Cache-Control:[no-cache] Content-Type:[video/mp2t] Date:[Sat, 24 Aug 2024 01:54:34 GMT]]
2024/08/23 21:54:34 Proxying xxx:10653 to http://xxx/06d998976b/7822876eecd7/45619
2024/08/23 21:54:34 Current number of connections for M3U_1: 1
2024/08/23 21:54:34 Received request from xxx:10655 for URL: /stream/dXMtYWJjLWhk
2024/08/23 21:54:35 [DEBUG] Successfully fetched stream from http://xxx/06d998976b/7822876eecd7/45439
2024/08/23 21:54:35 [DEBUG] Headers set for response: map[Access-Control-Allow-Origin:[*] Cache-Control:[no-cache] Content-Type:[video/mp2t] Date:[Sat, 24 Aug 2024 01:54:34 GMT]]
2024/08/23 21:54:35 Proxying xxx:10655 to http://xxx/06d998976b/7822876eecd7/45439
2024/08/23 21:54:35 Current number of connections for M3U_1: 2
2024/08/23 21:55:01 Stream ended (EOF reached): xxx:10653
2024/08/23 21:55:01 Exit code 1 received from http://xxx/06d998976b/7822876eecd7/45619
2024/08/23 21:55:01 Retrying other servers...
2024/08/23 21:55:01 Skipping M3U_1: marked as previous stream
2024/08/23 21:55:01 [DEBUG] All streams skipped in lap 0
2024/08/23 21:55:01 Error reloading stream for us-aande-hd: Error fetching stream. Exhausted all streams.
2024/08/23 21:55:01 http: superfluous response.WriteHeader call from main.streamHandler (stream_handler.go:164)
2024/08/23 21:55:01 Current number of connections for M3U_1: 1

**Comment by aniel300** [comment]
can u add a on the fly retry option for the same failed channel?

**Comment by sonroyaalmerol** [comment]
Merged #99 with the additional `MAX_RETRIES` config option

**Comment by aniel300** [comment]
sorry i wasent sure if this was a duplicate or not. keep me update on this, thanks

**Comment by sonroyaalmerol** [comment]
No problem, i've included it in the `0.12.0` release

**Comment by aniel300** [comment]
does the max retry works. am still getting the error posted above. probably because of this `2024/08/23 22:40:01 Skipping M3U_1: marked as previous stream` is there a way to make it retry the same provider/ stream on the fly without the client noticing?
